version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: near_wonders_db
      POSTGRES_USER: near_wonders_user
      POSTGRES_PASSWORD: near_wonders_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
